automount: autofsck while mount failed

diff --git a/package_files/others/sbin/arm64/automount b/package_files/others/sbin/arm64/automount
--- a/package_files/others/sbin/arm64/automount
+++ b/package_files/others/sbin/arm64/automount
@@ -45,10 +45,10 @@ case "$atteched_mode" in
 block,partition)
 	mkdir -p /var/log/automount
 	env > /var/log/automount/automount-$DEVTYPE-$(date +%Y%m%d%H%M%S)-$$-$ACTION.log
-	if [ "$ACTION" = remove ]
-	then
-		for disk in $(mount | awk '{print $1}' | grep /dev | egrep -v "mmcblk0|loop");do
-			part=$(mount | grep $disk | awk '{print $3}')
+	case "$ACTION" in
+	remove)
+		for disk in $(mount 2> /dev/null | awk '{print $1}' | grep /dev | egrep -v "mmcblk0|loop");do
+			part=$(mount 2> /dev/null | grep $disk | awk '{print $3}')
 			[ ! "$part" ] && continue
 			skip_umount=$(lsblk --list $disk > /dev/null 2>&1; echo $?)
 			if [ "$skip_umount" = 0 -a "$force_umount" != 1 ]
@@ -61,10 +61,8 @@ block,partition)
 			LOGGER "Successfully umounted invisible part [$part]"
 			[ ! "$(ls -A $part)" ] && rm -rf $part
 		done
-		LOGGER "umount: Finished"
-	fi
-	if [ "$ACTION" = add ]
-	then
+	;;
+	add)
 		if [ "$(get_config)" = 0 ]
 		then
 			LOGGER "Switch of automount is disabled, exit ..."
@@ -76,44 +74,49 @@ block,partition)
 			if [ "$(grep -v '#' /etc/fstab | grep -q $blk_id ; echo $?)" = 0 ]
 			then
 				LOGGER "UUID of /dev/$part detected in /etc/fstab, using [mount -a] command ..."
-				mnt_point=$(grep -v '#' /etc/fstab | grep $blk_id | awk '{print $2}')
+				mnt_point=$(grep -v '#' /etc/fstab 2> /dev/null | grep $blk_id | awk '{print $2}')
 				[ "$mnt_point" ] && mkdir -p $mnt_point && chmod 777 $mnt_point
 				mount -a
 				continue
 			fi
-			skip_mount=$(mount | awk '{print $1}' | grep -q $part ; echo $?)
-			fstype=$(blkid /dev/$part | egrep -o 'TYPE="[0-9a-zA-Z].+' | awk -F '["]' '/TYPE/{print $2}')
+			skip_mount=$(mount 2> /dev/null | awk '{print $1}' | grep -q $part ; echo $?)
+			fstype=$(blkid /dev/$part 2> /dev/null | egrep -o 'TYPE="[0-9a-zA-Z].+' | awk -F '["]' '/TYPE/{print $2}')
 			if [ -z "$fstype" ]
 			then
-				LOGGER "Unknown filesystem type of [/dev/$part]"
+				LOGGER "Unknown filesystem [/dev/$part]"
 				continue
 			fi
 			if [ "$skip_mount" = 0 ]
 			then
-				LOGGER "Already mounted [/dev/$part] on this device"
+				LOGGER "Already mounted [/dev/$part] at this device"
 				continue
 			fi
-			mkdir -p /mnt/$part
+			mkdir -p /mnt/$part || LOGGER "Failed to create directory [/mnt/$part] ..."
 			chmod 777 /mnt/$part
 			case "$fstype" in
 			ntfs)
 				extra_cmd="-o nls=utf8"
 			;;
-			vfat)
+			vfat | fat32)
 				extra_cmd="-o iocharset=utf8"
 			;;
-			*)
-				extra_cmd=""
-			;;
 			esac
-			LOGGER "Try to mount disk [/dev/$part]($fstype) on [/mnt/$part] ..."
-			mount -t $fstype /dev/$part /mnt/$part -o rw,defaults $extra_cmd && LOGGER "Successfully mounted disk [/dev/$part] on [/mnt/$part]" || {
-				LOGGER "Failed to mount disk [/dev/$part] on [/mnt/$part]"
-			}
+			LOGGER "Try to mount disk [/dev/$part]($fstype) at [/mnt/$part] ..."
+			mount -t $fstype /dev/$part /mnt/$part -o rw,noatime,nodiratime $extra_cmd
+			if [ "$?" != 0 ]
+			then
+				fsck -a /dev/$part
+				LOGGER "Retry to mount disk [/dev/$part]($fstype) after [File System Check] ..."
+				mount -t $fstype /dev/$part /mnt/$part -o rw,defaults $extra_cmd || {
+					LOGGER "Failed to mount disk [/dev/$part] at [/mnt/$part]"
+					continue
+				}
+			fi
+			LOGGER "Successfully mount disk [/dev/$part] at [/mnt/$part]"
 			sleep 1
 		done
-		LOGGER "mount: Finished"
-	fi
+	;;
+	esac
 ;;
 esac
 
